### ISSUE TITLE
Добавить валидацию полей при создании нового игрока

### ISSUE THREAD

**Issue by AntAresWeb** [Studio-Yandex-Practicum/adaptive_hockey_federation#166]
# Зачем?
При создании нового нового игрока вводимая иформация должна быть соответсвующей действительности.

# Как нужно делать?
Фамилия, имя, отчество игрока должны состоять из кирилических символов. Возможно использование дефиса.
Дата рождения игрока не должна быть позже определенной, устанавливаемой минимальным возрастом в годах. Минимальный возраст нужно указать в виде константы.

# Где?
core/constants.py
main/forms.py

**Comment by KonstantinRaikhert** [comment]
@BorisYP Привет! Как дела с новой таской?

**Comment by KonstantinRaikhert** [comment]
@ViacheslavMelnikov Предыдущий разработчки к сожалению пропал, таска твоя)

**Comment by KonstantinRaikhert** [comment]
@ViacheslavMelnikov Привет! Есть вопросы по таске?

**Comment by ViacheslavMelnikov** [comment]
Привет! Я внимательно посмотрел проект и свою таску. Мне нужно сделать валидацию полей при добавлении нового игрока. Валидацию решил делать используя виджеты и атрибуты. Создал проверку полей ФИО на кириллицу и дефис с помощью регулярных выражений. В проверке поля даты изменил форму поля с ТЕКСТА на ДАТЫ и ограничил ввод данных границей min & max. Осталось определить константу для проверки возраста и вставить рассчитываемые значения min & max в атрибуты виджета поля. Как-то так. Честно говоря планировал сегодня уже всё доделать, но вмешались обстоятельства. Может ещё и сделаю. Пока всё делал вспоминл о том, что я ещё ветку для себя не определил. :-) В четверг обязательно буду на связи.12.03.2024, 23:08, "Konstantin Raikhert" ***@***.***>:
@ViacheslavMelnikov Привет! Есть вопросы по таске?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
-- С уважением Мельников Вячеслав Александрович

**Comment by KonstantinRaikhert** [comment]
@ViacheslavMelnikov Прошу еще обратить внимания и во время создания моделей

**Comment by ViacheslavMelnikov** [comment]
Хорошо
